### ISSUE TITLE
Eventos en las ultimas 24 Horas.

### ISSUE THREAD

**Issue by le99** [Domotina/domotina#12]
En la historias de usuario "HUCEI-05 - Registro de eventos" dice:

Como Propietario yo quiero ver los eventos registrados en las ultimas 24 horas...

En el codigo parece que no se hace esta revision, almenos no en el metdo 
event_manager/views.py/place_view(request, pk)

**Comment by afesguerra** [comment]
Actualmente se puede ver TODOS los eventos y alarmas asociados a un inmueble, ordenados desde el más reciente hasta el más antiguo. Adicional a esto se muestra la fecha y hora en que se generaron, por lo que la historia de usuario sí se cumple, con el plus de poder ver TODOS los eventos además de las primeras 24 horas.
