### ISSUE TITLE
Se puede generar eventos con un tipo que no tienen que ver con el sensor.

### ISSUE THREAD

**Issue by le99** [Domotina/domotina#13]
Atravez de la interfaz REST para registrar eventos.
Por ejemplo se puede generar un evento de movimiento en uno de luz:

March 21, 2015, 4:41 p.m. - Sensor on Meeting Room Light reported Movement

Tambien se ve reflejado en las alarmas:

March 21, 2015, 4:41 p.m. - Alarm generated from Movement on Sensor on Meeting Room Light

**Comment by afesguerra** [comment]
Esto se solucionó al cambiar el valor de unicode en los sensores y quitar la tabla Event_Type. Por favor validar.

**Comment by afesguerra** [comment]
Solucionado.
