### ISSUE TITLE
En la tabla de evento se muestra "Toggle Power" aun cuando el sensor no a cambiado de estado.

### ISSUE THREAD

**Issue by le99** [Domotina/domotina#17]
Por ejemplo si se recibe un evento "ON" cuando la luz ya esta "ON" aparece lo siguiente:
Date    Time    Sensor  Type Sensor
March 23, 2015  9:01 p.m.   Sensor on   Toggle Power

**Comment by afesguerra** [comment]
Se cambiaron los datos que causaban esto.
