### ISSUE TITLE
Pagina de login con errores de stack trace.

### ISSUE THREAD

**Issue by le99** [Domotina/domotina#19]
En:
https://domotina-test.herokuapp.com/accounts/login/

Hay dos links:
"Reset it"
"Register"

Ninguno funciona pero muestra un stack trace de errores.
Uno tambien puede acceder a esta pagina intentando hacer login con credecianles incorrectas.

**Comment by raulgomezn** [comment]
Solución de bug:

> Pagina de login con errores de stack trace. #19
> En la rama Dev, pendiente para ser desplegada a Test. Se comentó esas opciones en el html.

**Comment by raulgomezn** [comment]
Luis E. cuando esté desplegado en Test porfa confirma y cierras este issue.

**Comment by le99** [comment]
Supongo que ya no esta el error, pero tampoco se puede crear un nuevo usuario...
