### ISSUE TITLE
Pop-ups sensores

### ISSUE THREAD

**Issue by le99** [Domotina/domotina#21]
Los pop-ups no funcionan como uno esperaria:
1) Al poner el mouse encima de la imagen de un sensor no se resalta el sensor.
2) Despues de tener el mouse un tiempo sobre el sensor no aparece el dialogo del estado del sensor.
3) El dialogo simpre aparece en la mitad de la imagen.

![popups](https://cloud.githubusercontent.com/assets/6639648/6868823/bea80c52-d45c-11e4-9ce8-41001007c9a0.png)

**Comment by afesguerra** [comment]
Se estableció que para ver los PopUp se hace clic en el sensor.
