### ISSUE TITLE
Error al cargar las imágenes en heroku

### ISSUE THREAD

**Issue by raulgomezn** [Domotina/domotina#30]
Al cargar un inmueble se muestra en blanco

> Failed to load resource: net::ERR_CONNECTION_REFUSED 
> http://domotina.host56.com/images/unlock_icon.png

El error parece ser que las imágenes en ese hosting murieron.

**Comment by raulgomezn** [comment]
Se solucionó cambiando de servicio de imágenes y se cambió el initial_data en Dev. djimenez13
Se cambió uno a uno en DevOps. djimenez13

**Comment by JuanMaChico** [comment]
no entiendo como arreglar el tema de las imágenes, alguien me podría ayudar!
