### ISSUE TITLE
Pop-up sin sensores

### ISSUE THREAD

**Issue by le99** [Domotina/domotina#31]
Cuando no hay sensores en la pagina (por ejemplo cuando se filtra por tempertaura pero no hay sensores de temperatura) y se preciona cualquier parte del mapa aparece un pop-up como el de la imagen:

![popup-sinsensores](https://cloud.githubusercontent.com/assets/6639648/7048001/b6eb8b74-ddd5-11e4-8ef5-4bd8d8783737.png)

El problema parece esta en el javascript de "map//templates/place_details.html"

**Comment by djimenez13** [comment]
Se procede a corregir el bug, verificando en javascript cuando no hay sensores registrados (bien sea por filtro o porque el inmueble no tiene registrado ninguno) y corrigiendo el método en views para que envíe null (None) cuando no hay registrado sensores.

**Comment by le99** [comment]
Volvio el problema:

![popup_sin_sensor](https://cloud.githubusercontent.com/assets/6639648/7221208/e4ee7b6e-e6a7-11e4-9db6-684607cbfc15.png)

**Comment by afesguerra** [comment]
Solucionado.
