### ISSUE TITLE
Unidades para los sensores continuos.

### ISSUE THREAD

**Issue by le99** [Domotina/domotina#34]
En el caso de los sensoreres de temperatura no hay unidades, no es lo mismo
Celsius, Kelvin o Farenheit.

Por lo menos se deberia documentar cual es la unidad que se esta usando.

**Comment by afesguerra** [comment]
En ninguna aparte de la interfaz se está mostrando el valor del evento ya que todos los estados tienen un nombre asociado. Actualmente para los sensores continuos también se muestra simplemente el nombre del estado que tiene el rango en el que se encuentra el sensor.
