### ISSUE TITLE
Se mezcla javascript y css en los archivos html

### ISSUE THREAD

**Issue by le99** [Domotina/domotina#48]
En el archivo "map/templates/place_details.html" hay un gran pedazo de javascript
que deberia estar en su propio arhcio .js

En el "map/templates/404.html" hay un monton de lineas de estilos que
deberian estar en su archivo .css

**Comment by afesguerra** [comment]
Yo ya corregí el de place_details para sacar la mayor cantidad posible de javascript a un archivo aparte. Luego reviso lo de 404.

**Comment by afesguerra** [comment]
Solucionado para el código nuestro. El 404 es una plantilla reutilizada y se dejará como está.
