### ISSUE TITLE
El metodo para cargar usuarios desde un archivo, no permite poner la clave.

### ISSUE THREAD

**Issue by le99** [Domotina/domotina#55]
Segun la interfaz el formato deberia ser: 
username,firstname,lastname,email,password

![batch_usuario_cualquier_archivo](https://cloud.githubusercontent.com/assets/6639648/7217324/3fdcc784-e5e9-11e4-800d-56ce3dbba079.png)

Pero la ultima columna password no se usa, de hecho a todos los usuarios se le asigna la misma
clave:DOMOTINA123

**Comment by CindyVHO** [comment]
Ya fue corregido, fue quitado la palabra password de la instrucción debido a que se tomo la decision de que todo usuario nuevo creado se le asignará la misma contraseña, esto debido a que despues un usuario puede entrar a cambiar su contraseña (HU no contemplada para los Sprints)
