### ISSUE TITLE
El control historico de eventos no se comporta como lo indica la historia de usuraio

### ISSUE THREAD

**Issue by le99** [Domotina/domotina#59]
Parece que al precionar el boton de "History" solo se muestra el estado actual del apartamento.
Sin importar el slider de la hora.

Pero segun la historia de usuario:
"Como propietario quiero seleccionar un evento y visualizar el estado de mi inmueble en dicho momento..."

Seleccionar algun evento no tiene ningun efecto sobre lo que se visualiza.

**Comment by afesguerra** [comment]
Solucionado
