### ISSUE TITLE
Al generar un reporte ¿Que deberia pasar si la fecha start es igual a end?

### ISSUE THREAD

**Issue by le99** [Domotina/domotina#69]
En este momento al poner la misma fecha nunca se genera un evento porque
start=end 
y no existe ningun evento para el cual
(start < event.timestamp < end)

Por ejemplo:
Poner start=2015/04/24, end=2015/04/24
No genera reporte pero

Poner start=2015/04/24, end=2015/04/25
Si generea un reporte:

![reporte](https://cloud.githubusercontent.com/assets/6639648/7333189/732cd84a-eb2a-11e4-863f-f2b19cb9e239.png)

¿Esto tiene sentido?

**Comment by afesguerra** [comment]
Es un bug, ya david se va a encargar de solucionarlo.

**Comment by djimenez13** [comment]
Luego de hablar con el Product Owner, se tomó la decisión que se construiría la solución para que el sistema acepte dos fechas iguales, aún cuando en los escenarios de aceptación no estuviera descrito.
