### ISSUE TITLE
En Firefox input type="date" se muestra como un input normal.

### ISSUE THREAD

**Issue by le99** [Domotina/domotina#70]
Esto es confuso porque toca ingresar la fecha como un String en formato:
YYYY-MM-DD

Esto afecta la interaccion en particular en map History, como se ve en la figura:

![history_go](https://cloud.githubusercontent.com/assets/6639648/7374262/ce5581cc-ed96-11e4-969a-bddaf4b3a30f.png)

**Comment by djimenez13** [comment]
Al parecer este tipo de input html5 no lo soporta firefox.

Ver detalle: http://www.wufoo.com/html5/types/4-date.html

Una alternativa podría ser utilizar datetime-picker de bootstrap.
