### ISSUE TITLE
Monthly report generator no fucniona con Diciembre

### ISSUE THREAD

**Issue by le99** [Domotina/domotina#72]
Al intentar sacar el reporte de Diciembre aparece:

![december_error](https://cloud.githubusercontent.com/assets/6639648/7441517/b259927a-f0b0-11e4-8116-b45e5cb0c4b3.png)

Esto parece que es porque en: "report_manager/central_report_gen.py"
En la fucnion "validation_entry"
Se usa:

``` python
if not month in range(1, 12):
```

El problema es que Diciembre es el mes 12
Entonces:

``` python
(12 in range (1,12)) == False
```

**Comment by lfmendivelso10** [comment]
Listo, ya se hizo el cambio correspondiente.

**Comment by raulgomezn** [comment]
Felipe commit y push para que todos lo vean :+1:

**Comment by lfmendivelso10** [comment]
Listo, ya hice el push.
