### ISSUE TITLE
Usando REST se puede cambiar la posicion de un sensor que no sea "Movement"

### ISSUE THREAD

**Issue by le99** [Domotina/domotina#9]
El servicio REST recibe los datos de los sensores, como un sensor de luz
no indica la posicion no tiene sentido que se pueda cambiar la posicion usando este servicio REST.

Nota: Se supone que no tenemos control sobre el sistema de sensores y los errores 
de estos sistemas no deberian propagarse a nuestro sistema.

**Comment by raulgomezn** [comment]
Toca revisar si es un bug u oportunidad de mejora.
